services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: IhebPFE
      POSTGRES_PASSWORD: ihebA1118
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: report_gen_builder
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-ooredoo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-ooredoo:
    driver: bridge

volumes:
    postgres:
      driver: local

