spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/report_gen_builder
    username: postgres
    password: iheb1118
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  file:
    upload-dir: ./uploads
  mail:
    host: localhost
    port: 1025
    username: iheb
    password: iheb1
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
          connectiontimeout: 10000
          timeout: 4000
          writetimeout: 10000
  application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000


    mailing:
      frontend:
        activation-url: http://localhost:4200/activation-account


